import fs from "node:fs/promises";
import path from "node:path";
import { config } from "./config.js";

// One interface, three drivers. This is the exit path ADR-003 depends on:
// Vercel Blob today, R2 tomorrow, MinIO on a UNGRD server the day after —
// nothing outside this file knows which.
export interface StoragePort {
  put(key: string, body: Buffer, mime: string): Promise<{ key: string; url?: string }>;
  get(key: string): Promise<Buffer>;
  del(key: string): Promise<void>;
  publicUrl(key: string): string | null;
}

class FsStorage implements StoragePort {
  constructor(private root: string) {}
  private p(key: string) {
    // Defence against traversal: keys are generated by us, but never trust that.
    const safe = key.replace(/\.\./g, "").replace(/^\/+/, "");
    return path.join(this.root, safe);
  }
  async put(key: string, body: Buffer) {
    const f = this.p(key);
    await fs.mkdir(path.dirname(f), { recursive: true });
    await fs.writeFile(f, body);
    return { key };
  }
  async get(key: string) {
    return fs.readFile(this.p(key));
  }
  async del(key: string) {
    await fs.rm(this.p(key), { force: true });
  }
  publicUrl(key: string) {
    return config.storage.publicBaseUrl ? `${config.storage.publicBaseUrl}/${key}` : null;
  }
}

class MemoryStorage implements StoragePort {
  private m = new Map<string, Buffer>();
  async put(key: string, body: Buffer) {
    this.m.set(key, body);
    return { key };
  }
  async get(key: string) {
    const b = this.m.get(key);
    if (!b) throw new Error(`no such key: ${key}`);
    return b;
  }
  async del(key: string) {
    this.m.delete(key);
  }
  publicUrl() {
    return null;
  }
}

// S3-compatible (R2, S3, MinIO). Loaded lazily so the image does not carry the
// AWS SDK when running against the filesystem driver.
class S3Storage implements StoragePort {
  private client: any;
  private async c() {
    if (!this.client) {
      const { S3Client } = await import("@aws-sdk/client-s3" as any);
      this.client = new S3Client({
        region: config.storage.region,
        endpoint: config.storage.endpoint || undefined,
        forcePathStyle: !!config.storage.endpoint,
        credentials: {
          accessKeyId: config.storage.accessKeyId,
          secretAccessKey: config.storage.secretAccessKey,
        },
      });
    }
    return this.client;
  }
  async put(key: string, body: Buffer, mime: string) {
    const { PutObjectCommand } = await import("@aws-sdk/client-s3" as any);
    await (await this.c()).send(
      new PutObjectCommand({ Bucket: config.storage.bucket, Key: key, Body: body, ContentType: mime })
    );
    return { key, url: this.publicUrl(key) ?? undefined };
  }
  async get(key: string) {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3" as any);
    const r = await (await this.c()).send(
      new GetObjectCommand({ Bucket: config.storage.bucket, Key: key })
    );
    const chunks: Buffer[] = [];
    for await (const ch of r.Body as any) chunks.push(Buffer.from(ch));
    return Buffer.concat(chunks);
  }
  async del(key: string) {
    const { DeleteObjectCommand } = await import("@aws-sdk/client-s3" as any);
    await (await this.c()).send(
      new DeleteObjectCommand({ Bucket: config.storage.bucket, Key: key })
    );
  }
  publicUrl(key: string) {
    return config.storage.publicBaseUrl ? `${config.storage.publicBaseUrl}/${key}` : null;
  }
}

export const storage: StoragePort =
  config.storage.driver === "s3"
    ? new S3Storage()
    : config.storage.driver === "fs"
    ? new FsStorage(config.storage.rootDir)
    : new MemoryStorage();

export function mediaKey(caseId: string, id: string, ext: string) {
  return `cases/${caseId.slice(0, 2)}/${caseId}/${id}.${ext}`;
}
